models/contact.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))
    
    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from utils.db import db
from config import database_connection_uri

app = Flask(__name__)

app.secret_key = 'secret_key'
app.config['SQLALCHEMY_DATABASE_URI'] = database_connection_uri
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)

@contacts.route('/')
def index():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)

@contacts.route('/new', methods=['POST'])
def add_contact():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']
    
    new_contact = Contact(fullname, email, phone)
    
    db.session.add(new_contact)
    db.session.commit()
    
    flash('Contact added successfully')
    
    return redirect(url_for('contacts.index'))

@contacts.route('/about')
def about():
    return render_template('about.html')

@contacts.route('/update/<int:id>', methods=['GET', 'POST'])
def update_contact(id):
    contact = Contact.query.get(id)
    if request.method == 'POST':
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']
        
        db.session.commit()
        
        flash('Contact updated successfully')
        
        return redirect(url_for('contacts.index'))
    return render_template('update.html', contact=contact)

@contacts.route('/delete/<int:id>')
def delete_contact(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    
    flash('Contact deleted successfully')
    
    return redirect(url_for('contacts.index'))

templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1>About</h1>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur
        nesciunt ipsam eligendi. Officia quis culpa delectus nostrum facere unde
        optio beatae? Similique explicabo, rerum voluptatum maxime veritatis illum
        ex officia doloremque. Ipsum repudiandae perferendis ipsa rerum distinctio
        eveniet molestiae voluptatem omnis, debitis sequi dignissimos maxime
        deserunt quis tenetur dolore animi ullam asperiores nesciunt aut. Eos
        repellendus ratione molestiae minus beatae, labore excepturi quam est enim
        magni obcaecati unde dicta officia dolorem ut officiis, voluptatem, quos
        repudiandae et explicabo nulla ducimus natus quibusdam pariatur. Id, quae
        soluta illo perspiciatis sequi asperiores ad quibusdam dolor mollitia ipsa!
        Velit aperiam vitae iste dolorem voluptates sint excepturi quaerat
        accusantium veniam mollitia optio, asperiores aspernatur temporibus? Minus
        delectus officiis iure quia fuga autem blanditiis laboriosam asperiores eos
        nemo. Sunt ipsam sequi, corporis inventore eius hic ullam fugiat velit
        voluptates nobis aut, atque nostrum quae quam, aliquid natus facilis
        nesciunt assumenda culpa amet exercitationem. Quas alias, esse enim commodi
        possimus quam nam molestiae nobis doloremque labore neque illo ullam
        necessitatibus blanditiis voluptates sunt eos quis aspernatur doloribus
        ratione dolorum in autem ex! Architecto aspernatur laboriosam consectetur
        illo cumque doloribus aut ad amet molestias voluptatem nulla perspiciatis
        voluptate, culpa expedita delectus odio pariatur et error ipsum ab!
        Perspiciatis magnam ut nemo dolore deleniti iure adipisci. Consequatur
        debitis dolorum et nam odio fugit ipsam doloribus facilis facere at, ducimus
        accusantium rerum, quia fugiat itaque repudiandae repellat eius laborum
        ipsum atque dolorem magnam excepturi enim. Quo culpa aliquam assumenda
        molestiae perferendis earum, itaque ipsum ex eligendi pariatur, consequatur
        labore velit dolor distinctio error laudantium soluta voluptates impedit
        minus deserunt? Quod veritatis numquam, nostrum quaerat eos non esse quasi
        quas, molestias libero omnis consequatur labore corporis itaque iusto
        incidunt fuga eum nam inventore odit rerum, et repellendus! Laboriosam, sed
        sint libero in natus optio molestias labore assumenda odio delectus
        repellendus!
    </p>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block content %}
    

    <div class="row">

        <div class="col-md-5">
            {% include 'partials/_message.html' %}

            {% include 'partials/_contactsForm.html' %}
        </div>

        <div class="col-md-7">
            {% for contact in contacts %}
                <div class="card mb-1 text-white bg-dark">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <h5>{{ contact.fullname }}</h5>
                            <div>
                                <a href="{{url_for('contacts.update_contact', id=contact.id)}}"
                                class="btn bg-black text-white btn-sm rounded-0">Update</a
                                >
                                <a href="{{url_for('contacts.delete_contact', id=contact.id)}}"
                                class="btn btn-danger btn-sm rounded-0">Delete</a
                                >
                            </div>
                        </div>
                        <p>{{ contact.email }}</p>
                        <p>{{ contact.phone }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Flask SQLAlchemy CRUD</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    </head>
    <body>
        {% include('partials/_navbar.html') %}

        <div class="container p-2">
            {% block content %} {% endblock %}
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
        
    </body>
</html>

templates/partials/_contactsForm.html
<form action="/new" method="POST" class="card bg-dark text-light">
    <div class="card-body p-4">
        <div class="mb-3">
            <label for="fullname">Write your fullname:</label>
            <input type="text" name="fullname" placeholder="Write your fullname" class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>
        
        <div class="mb-3">
            <label for="email">Write your email:</label>
            <input type="text" name="email" placeholder="Write your email" class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>
        
        <div class="mb-3">
            <label for="phone">Write your phone:</label>
            <input type="text" name="phone" placeholder="Write your phone" class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>
        
    
        <button class="btn btn-primary">Save</button>
    </div>
</form>

templates/partials/_message.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{{url_for('contacts.index')}}">Flask SQLAlchemy CRUD</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('contacts.about')}}">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/update.html
{% extends 'layout.html' %}
{% block content %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <form action="{{url_for('contacts.update_contact', id=contact.id)}}" method="post" class="card bg-dark text-white ">
            <div class="card-body p-4">
                <div class="mb-3">
                    <label for="fullname">Write your fullname:</label>
                    <input type="text" name="fullname" id="fullname" placeholder="Write your full name"
                    value="{{contact.fullname}}"
                    class="form-control rounded-0 bg-dark border-0 text-white" >
                </div>
                <div class="mb-3">
                    <label for="email">Update your email:</label>
                    <input type="text" name="email" id="email" placeholder="Write your email"
                    value="{{contact.email}}"
                    class="form-control rounded-0 bg-dark border-0 text-white" >
                </div>
                <div class="mb-3">
                    <label for="phone">Write your phone:</label>
                    <input type="text" name="phone" id="phone" placeholder="Write your phone"
                    value="{{contact.phone}}" 
                    class="form-control rounded-0 bg-dark border-0 text-white" >
                </div>
                <button class="btn btn-secondary">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}